# Generated by Django 2.2.1 on 2019-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('CVL', 'CIVIL'), ('CS', 'CSE'), ('EC', 'ECE'), ('EE', 'EEE'), ('EI', 'EI'), ('IB', 'IBT'), ('IT', 'IT'), ('MC', 'MECHANICAL'), ('PD', 'PRODUCTION')], default='CVL', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(choices=[('frst', 'FIRST'), ('sec', 'SECOND'), ('thrd', 'THIRD'), ('frth', 'FOURTH')], default='frst', max_length=6),
        ),
    ]
