# Generated by Django 2.2.1 on 2019-09-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190922_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='accounts.StudentProfile')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rollno', to='accounts.StudentProfile')),
            ],
        ),
    ]
