# Generated by Django 2.2.1 on 2019-09-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='name',
        ),
    ]
