# Generated by Django 2.2.1 on 2019-09-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studentexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EI', 'EI'), ('IBT', 'IBT'), ('IT', 'IT'), ('MECHANICLA', 'MECHANICAL'), ('PRODUCTION', 'PRODUCTION')], default='CIVIL', max_length=10),
        ),
    ]
